In [1]:
# This script contains exercises on 
# manipulating arrays with numpy
import numpy as np
x = np.arange(0, 3**3)

#### 1. What is the length of x?

In [2]:
# Your code here
len(x)

27

#### 2. How do you get the first value out of x?

In [3]:
# Your code here
x[0]

np.int64(0)

#### 3. How do you get the last value out of x?

In [ ]:
x[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#### 4. How do you get the first 5 values out of x?

In [ ]:
# Your code here

#### 5. What about the last 5 values of x?

In [ ]:
# Your code here

#### 6. How do you get every other value out of x?

In [8]:
# Your code here
x[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])


#### 7. Get the first 9 values of x, and reshape them to a 3x3 matrix. Assign this matrix to the variable `y`

In [12]:
x.reshape?

Docstring:
a.reshape(shape, /, *, order='C', copy=None)

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(10, 11)`` is equivalent to
``a.reshape((10, 11))``.
Type:      builtin_function_or_method

#### 8. How do you get the middle value out of y?

In [ ]:
y = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
])
# Your code here

#### 9. How do you get the first row out of y?

In [ ]:
# Your code here

#### 10. How do you get the first column out of y?

In [ ]:
# Your code here

#### 11. Reshape x into a 3x3x3 cube. Assign this to the variable `z`

In [13]:
x.shape

(27,)

In [15]:
x = np.arange(0, 3**3)
z = x.reshape(3,3,3)
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### 12. How do you get the "center" value from z?

In [4]:
z = np.array([
    [[ 0, 1, 2],
     [ 3, 4, 5],
     [ 6, 7, 8]],
    [[ 9,10,11],
     [12,13,14],
     [15,16,17]],
    [[18,19,20],
     [21,22,23],
     [24,25,26]]
])
# Your code here


#### 13. How do you take the total sum of z?

In [25]:
# Your code here
np.sum(z, axis=1)

array([[ 9, 12, 15],
       [36, 39, 42],
       [63, 66, 69]])


#### 14. How do you take the sum along the first dimension of z?

In [17]:
z

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [16]:
# Your code her
z.sum(axis=0)

array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

#### 15. How do you take the sum along the last dimension of z?

In [20]:
# Your code here
z.sum(axis=-1)

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])

In [26]:
np.sum(z, axis=-1)

array([[ 3, 12, 21],
       [30, 39, 48],
       [57, 66, 75]])